# HW 03 - Part 2: Data Exploration

---
---
**DISCLAIMER: This is a fake story, not a real incident! We have created this story just for the data exploration purpose.**

---
---

**Campus Police Department**

Incident Report

---

**Incident Date:** September 10, 2025

**Location of Incident:** 2nd Floor, Iribe Building

**Items Left at the Scene:** Red Ticket for Zichao's Magic Show

**Case Number:** 2025-IRB-0027

---
**Victim Information:**

**Name:** Dr. Fardina Alam

**Affiliation:** University of Maryland, College Park

**Position:** Professor

**Contact Information:** fardina@umd.edu

---

**Incident Description:**

On the evening of September 10, 2025, an unknown individual(s) unlawfully entered Dr. Fardina's room located on the 2nd floor of Iribe and stole a set of Markers. The stolen items were a set of limited edition markers that Dr. Fardina had spent years collecting. At the scene of the crime, a red entry ticket for "Zichao's Magic Show" was found on the floor near Dr. Fardina's desk.

In [1]:
# We import all essential libraries for this HW; if you want to add additional libraries, you can add more here!
import pandas as pd
from datetime import datetime

## Instructions:

In this assignment, you are tasked with solving the mystery of Dr. Fardina's stolen markers and finding the culprit.

* To accomplish this, you will be provided with **4 data sets** containing key information related to the incident. The list of the data sets name given below:

 - Profiles
 - Witnesses
 - Zichao's magic show
 - Interrogation Statements



* Your goal is to analyze these data sets to uncover the clues and evidences that will lead you to the thief.

**Be careful in following instructions as it may lead to you losing points :(**

Take a moment to look at all the data sets below:

---

**Profiles:**

This dataset contains information regarding all the potential people that could have committed the crime. General information regarding each person are as follows:
- **ID:** A **unique** identification for each person
- **Name:** The name of the person
- **Birthday:** The birthday of the person
- **Location_during_crime:** The location of the person during the crime
- **Eye_Color:** The eye color of the person
- **Skin_Color:** The skin color of the person
- **Hair_Color:** The hair color of the person
- **Height:** The height of the person in cm

**Witnesses:**

This dataset contains a statement from everyone in profiles, regarding suspicious things they saw during the time of the crime. Information that comes in this dataset are as follows:
- **ID:** A **Unique** identification for each person
- **Statement:** A statement from the person regarding a suspicious activity during the time of the crime

**Zichao's magic show:**

This dataset contains everyone that purchased a ticket for the show. **NOTE** that not everyone in profiles has purchased a ticket for this show. The Information contained in this dataset are as follows:
- **ID:** A **Unique** indentification for each person
- **Ticket_Number:** A **Unique** number that serves as an identification for the ticket bought

**Interrogation Statements:**

This datasets contains a statement from each person after they have been interrogated. **NOTE** assume that each statement is 100% true and that there are people who aren't in "Profiles" in this dataset. The Information contained in this dataset are as follows:

- **Name:** The name of the person being interrogated
- **Statement:** A statement the person gives after being interrogated

---

## Instructions for the Students:

In this assignment, you are tasked with solving the mystery of Dr. Fardina's stolen markers and finding the culprit.

* To accomplish this, you will be provided with **4 data sets** containing key information related to the incident. The list of the data sets name given below:

 - Profiles
 - Witnesses
 - Zichao's magic show
 - Interrogation Statements



* Your goal is to analyze these data sets to uncover the clues and evidences that will lead you to the thief.

**Be careful in following instructions as it may lead to you losing points :(**

Take a moment to look at summary of all the data sets below:

---

**Profiles:**

This dataset contains information regarding all the potential people that could have committed the crime.

**Witnesses:**

This dataset contains a statement from everyone in profiles, regarding suspicious things they saw during the time of the crime.

**Zichao's magic show:**

This dataset contains everyone that purchased a ticket for the show. **NOTE** that not everyone in profiles has purchased a ticket for this show. In this dataset, there is a column named  **"Ticket_Number"** which is an **Unique** number that serves as an identification for the ticket bought.

**Interrogation Statements:**

This datasets contains a statement from each person after they have been interrogated. **NOTE** assume that each statement is 100% true and that there are people who aren't in "Profiles" in this dataset.

---

## Q1) Lets begin by observing the profiles dataset


**TASK 1.1 (1 Point):**  In the code box below, load in "Profiles" dataset into a variable called **profiles_df** and display it

In [2]:
profiles_df = pd.read_csv('Profiles.csv')

**TASK 1.2 (1 Point):**  Next, you need to display the number of rows and columns in the "Profiles" dataset.

In [3]:
profiles_df.shape

(348, 8)

**TASK 1.3 (1 Point):**  Next, you need to display the name of the columns in the "Profiles" dataset.

In [4]:
profiles_df.columns

Index(['ID', 'Name', 'Birthday', 'Location_during_crime', 'Eye_Color',
       'Skin_Color', 'Hair_Color', 'Height'],
      dtype='object')

**TASK 1.4 (1 Point):**  Now, you need to display the types of the columns in the "Profiles" dataset.

In [5]:
profiles_df.dtypes

ID                       object
Name                     object
Birthday                 object
Location_during_crime    object
Eye_Color                object
Skin_Color               object
Hair_Color               object
Height                    int64
dtype: object

**TASK 1.5 (2 Points):** Utilizing the .count() function on this dataset and set it to the variable **info** and then display it. Write any **potential problem** that you see with the dataset when observing the output of the count function:

In [6]:
info = profiles_df.count()
print(info)

ID                       348
Name                     348
Birthday                 348
Location_during_crime    280
Eye_Color                280
Skin_Color               348
Hair_Color               348
Height                   348
dtype: int64

*Write your observations here:*
One potential issue is the missing values of the Location_during_crime and Eye_color variables

**TASK 1.6 (4 Points):** Look back at the "Profiles" dataset. Using other pandas functions than count(), can you spot another potential problem with the dataset?

In [7]:
print(f"possible duplicates: {len(profiles_df[profiles_df.duplicated()])}")
profiles_df.head(10)

possible duplicates: 48

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height
0,P299,James Mason,1968/07/10,fourth floor,red,indigo,orange,191
1,P086,Christopher Rodriguez,1978/03/10,second floor,indigo,indigo,green,198
2,P022,Misty Ashley,1989/10/08,fourth floor,blue,red,violet,154
3,P003,Amanda Brown,1995/27/10,lobby,green,blue,violet,158
4,P036,William Jones,1990/26/02,fourth floor,blue,yellow,orange,184
5,P158,Karen Roberts,05/11/1981,NaN,NaN,yellow,blue,172
6,P129,Calvin Powers,1999/22/06,fourth floor,indigo,blue,orange,199
7,P181,Kaitlin Higgins PhD,07/22/1963,third floor,NaN,violet,violet,196
8,P136,Jodi Mccarty,1987/22/07,NaN,orange,orange,red,198
9,P157,Ronald Jackson,1973/23/04,second floor,blue,red,red,200

*Write your observation here:*

Another potential problem is likely that the dates in the Birthday column have inconsistent formats and are stored as strings. Also there appears to be a few duplicate entries in the dataframe, but I'm unsure if this will cause issues in the analysis later on.

## Q2) Cleaning the data set

**TASK 2.1 (10 Points):** Lets begin by fixing the Birthday column. You may notice that the dates are in inconsistent format!

- Pandas internally represent dates in 'datetime64' format which is a form of ISO 8601. Basically, dates are represented as yyyy-mm-dd.


- Fix all the dates in the Birthday Column.
- Display the "Profiles" dataframe after you are done.
- Note that the only 2 formats the dates are in is either yyyy/dd/mm or mm/dd/yyyy, you want to represent them as yyyy-mm-dd


**HINT:** some datetime functions might make things easier.
- https://www.geeksforgeeks.org/python-pandas-to_datetime/
- https://www.programiz.com/python-programming/datetime/strftime

In [8]:
# Your Code here

profiles_df['Birthday'] = [
    pd.to_datetime(d, format='%Y/%d/%m') 
    if d[4] == '/' 
    else pd.to_datetime(d, format='%m/%d/%Y')
    for d in profiles_df['Birthday']
]

profiles_df

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height
0,P299,James Mason,1968-10-07,fourth floor,red,indigo,orange,191
1,P086,Christopher Rodriguez,1978-10-03,second floor,indigo,indigo,green,198
2,P022,Misty Ashley,1989-08-10,fourth floor,blue,red,violet,154
3,P003,Amanda Brown,1995-10-27,lobby,green,blue,violet,158
4,P036,William Jones,1990-02-26,fourth floor,blue,yellow,orange,184
...,...,...,...,...,...,...,...,...
343,P126,Kenneth Watson,1987-01-03,NaN,violet,indigo,red,176
344,P203,Donald Anderson,1964-09-26,third floor,yellow,indigo,orange,193
345,P273,Harold Watkins,2002-07-12,fourth floor,blue,indigo,red,193
346,P290,Brandon Bennett,1993-10-03,third floor,NaN,yellow,indigo,161
347,P233,Karen Lambert,1981-06-27,second floor,red,yellow,orange,169

**TASK 2.2 (5 Points):** Now that we have cleaned up the Birthday column, lets find the age of each person. Create a new column called "Age" that displays the age of the person **on the day of the crime.** Once you are done, display the
"Profiles" dataframe

In [9]:
# Write your code here
def calc_age(birthday):
    crime_day = pd.to_datetime('2025-09-10', format='%Y-%m-%d')
    return crime_day.year - birthday.year - ((crime_day.month, crime_day.day) < (birthday.month, birthday.day))

profiles_df['Age'] = profiles_df['Birthday'].apply(calc_age)
profiles_df

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height,Age
0,P299,James Mason,1968-10-07,fourth floor,red,indigo,orange,191,56
1,P086,Christopher Rodriguez,1978-10-03,second floor,indigo,indigo,green,198,46
2,P022,Misty Ashley,1989-08-10,fourth floor,blue,red,violet,154,36
3,P003,Amanda Brown,1995-10-27,lobby,green,blue,violet,158,29
4,P036,William Jones,1990-02-26,fourth floor,blue,yellow,orange,184,35
...,...,...,...,...,...,...,...,...,...
343,P126,Kenneth Watson,1987-01-03,NaN,violet,indigo,red,176,38
344,P203,Donald Anderson,1964-09-26,third floor,yellow,indigo,orange,193,60
345,P273,Harold Watkins,2002-07-12,fourth floor,blue,indigo,red,193,23
346,P290,Brandon Bennett,1993-10-03,third floor,NaN,yellow,indigo,161,31
347,P233,Karen Lambert,1981-06-27,second floor,red,yellow,orange,169,44

**TASK 2.3 (10 Points):** Now that we have created the "age"; lets clean the 'Eye_color's column.

***Please read the directions carefully:***


- In order to fill in the missing eye_colors, we want to find the **most common eye_color** among those who have the **same hair and skin color**.
- For Instance, if we want to find the eye_color of someone who has yellow hair and violet skin:
 - we would first find everything who has the same hair and skin color, in this case it would be yellow hair and violet skin
 - and then we find the most common eye_color among them.
 - we then replace the missing eye_color with the eye color that is the most common among the people with the same hair and skin color.
- Watch out for redundant data!

- ***FIX: In the case that you find multiple modes, choose the color that appears first in alphabetical order***

 When you finish filling in the missing eye colors, please display the profiles_df

In [10]:
# Write your code here
def fill_eye_color(group):
    eye_colors = group['Eye_Color'].mode()
    most_common_color = eye_colors.sort_values().iloc[0]
    
    group['Eye_Color'] = group['Eye_Color'].fillna(most_common_color)
    return group

profiles_df = profiles_df.groupby(['Hair_Color', 'Skin_Color'], group_keys=False).apply(fill_eye_color, include_groups=True)

profiles_df

C:\Users\Family\AppData\Local\Temp\ipykernel_13748\1216185046.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  profiles_df = profiles_df.groupby(['Hair_Color', 'Skin_Color'], group_keys=False).apply(fill_eye_color, include_groups=True)

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height,Age
0,P299,James Mason,1968-10-07,fourth floor,red,indigo,orange,191,56
1,P086,Christopher Rodriguez,1978-10-03,second floor,indigo,indigo,green,198,46
2,P022,Misty Ashley,1989-08-10,fourth floor,blue,red,violet,154,36
3,P003,Amanda Brown,1995-10-27,lobby,green,blue,violet,158,29
4,P036,William Jones,1990-02-26,fourth floor,blue,yellow,orange,184,35
...,...,...,...,...,...,...,...,...,...
343,P126,Kenneth Watson,1987-01-03,NaN,violet,indigo,red,176,38
344,P203,Donald Anderson,1964-09-26,third floor,yellow,indigo,orange,193,60
345,P273,Harold Watkins,2002-07-12,fourth floor,blue,indigo,red,193,23
346,P290,Brandon Bennett,1993-10-03,third floor,yellow,yellow,indigo,161,31
347,P233,Karen Lambert,1981-06-27,second floor,red,yellow,orange,169,44


## Q3) Finding the features of the culprit

Now that we have successfully cleaned all of our data, lets begin finding the features of the criminal. Take a moment to look at the **"Witnesses"** table. We don't necessarily want all the statements from every single witness.

**NOTE:** Take a look at the structure of each statement, notice how there are only a few variations of statements from the witnesses.

**TASK 3.1 (5 Points):** Find all witnesses that were near the crime scene
- First load in the Witness.csv file and set it to a variable called "**witness_df**"
- create a new dataframe called **"important_witnesses"** that contains the id and the witness statements of those who were near the scene of the crime
- display the new dataframe when you are finished
- **HINT:** look at the floor which the crime happened on.

In [11]:
# Write your code here
witness_df = pd.read_csv('Witness.csv')

important_IDs = profiles_df[profiles_df['Location_during_crime'] == 'second floor']['ID']

important_witnesses = witness_df[witness_df['ID'].isin(important_IDs)].copy()
important_witnesses.reset_index(drop=True, inplace=True)
important_witnesses

      ID                                          Statement
0   P150  I saw someone with orange hair acting suspicious.
1   P075  I saw someone with orange hair acting suspicious.
2   P058   I saw someone with green eyes acting suspicious.
3   P157  I saw someone who looked 152 cm tall acting su...
4   P139  I saw someone who looked 150 cm tall acting su...
..   ...                                                ...
57  P015  I saw someone with orange hair acting suspicious.
58  P268  I saw someone that looks to be 21 years old ac...
59  P077  I saw someone with orange eyes acting suspicious.
60  P168     I saw someone with red skin acting suspicious.
61  P145  I saw someone with orange eyes acting suspicious.

[62 rows x 2 columns]

**TASK 3.2 (10 Points):** Find every potential eye color that the culprit could have

 - Put all the potential eye colors of the culprit in a list called **"potential_eye_colors"** and display it when you're done. potential_eye_colors should have **no duplicates.**

In [12]:
# Write your code here
def get_feature_list(statements, key_word):
    feature_list = []
    filtered_statements = statements[statements.str.contains(key_word, case=False)]
    
    for statement in filtered_statements:
        left = statement.split(key_word)[0]
        
        feature = left.split()[-1]
        if feature not in feature_list:
            feature_list.append(feature)

    return feature_list
    
potential_eye_colors = get_feature_list(important_witnesses['Statement'], 'eyes')
potential_eye_colors

['green', 'orange', 'blue', 'violet']

**TASK 3.3 (5 Points):** Find every potential hair color that the culprit could have

 - Put all the potential hair colors of the culprit in a list called **"potential_hair_colors"** and display it when you're done

In [13]:
# Write your code here
potential_hair_colors = get_feature_list(important_witnesses['Statement'], 'hair')
potential_hair_colors

['orange', 'green', 'blue', 'violet']

**TASK 3.4 (5 Points):** Find every potential skin color that the culprit could have

 - Put all the potential skin colors of the culprit in a list called **"potential_skin_colors"** and display it when you're done

In [14]:
# Write your code here
potential_skin_colors = get_feature_list(important_witnesses['Statement'], 'skin')
potential_skin_colors

['orange', 'red', 'green']

**TASK 3.5 (10 Points):** Find the potential height of the culprit

 - Put the smallest and largest potential heights of the culprit in the variables called **"smallest_height" & "largest_height"** and display them when you are done

In [15]:
# Write your code here
height_list = get_feature_list(important_witnesses['Statement'], 'cm tall')
potential_heights = [int(height) for height in height_list]

if potential_heights:
    smallest_height = min(potential_heights)
    largest_height = max(potential_heights)

print(f"smallest height: {smallest_height} \nlargest height: {largest_height}")

smallest height: 150
largest height: 170

**TASK 3.6 (8 Points):** Find the potential age of the culprit

 - Put the smallest and largest potential age of the culprit in the variables called **"smallest_age" & "largest_age"** and display them when you are done

In [16]:
# Write your code here
age_list = get_feature_list(important_witnesses['Statement'], 'years old')
potential_ages = [int(age) for age in age_list]

if potential_ages:
    smallest_age = min(potential_ages)
    largest_age = max(potential_ages)

print(f"smallest age: {smallest_age} \nlargest age: {largest_age}")

smallest age: 21
largest age: 35

## Q4) Finding who ones the ticket

**TASK 4.1 (2 Points):** Loading final dfs


Load in the **"Zichao's Magic Show.csv"** into a dataframe called **"show_df"** and the **"Interrogation_Statement.csv"** into a dataframe called **"interrogation_df"** respectively and display them when you are done

In [17]:
# Write your code here
show_df = pd.read_csv('Zichao_s Magic Show.csv')
interrogation_df = pd.read_csv('Interrogation_Statements.csv')


**TASK 4.2 (8 Points):** Create a column called **Ticket_Color** for the **"show_df"** that displays all the colors of the ticket

Remember that there was a show ticket left at the crime scene, take a second to look through **"show_df"**. Try and find a way to identify how you can find the ticket color from the ticket number.

display the **"show_df"** when you are done

**HINT:** examine the **"interogation_df"**

In [18]:
# Write your code here
def get_color(tic_num):
    s = 0

    while tic_num > 0:
        s += tic_num % 10
        tic_num //= 10

    last_digit = s % 10
    
    if last_digit in [0, 1, 2]:
        color = 'blue'
    if last_digit in [3, 4, 5]:
        color = 'red'
    if last_digit in [6, 7]:
        color = 'green'
    if last_digit in [8, 9]:
        color = 'yellow'

    return color

show_df['Ticket_Color'] = show_df['Ticket_Number'].apply(get_color)
show_df

       ID  Ticket_Number Ticket_Color
0    P132       50269975          red
1    P056       28120732          red
2    P250       88051289         blue
3    P197       79545169        green
4    P012       83521845        green
..    ...            ...          ...
146  P121       31341288         blue
147  P003       85008158          red
148  P180       24491860          red
149  P283       38524355          red
150  P142        2238676          red

[151 rows x 3 columns]

## Q5) Finding the culprit

A helpful function might be the "iloc" function. Have a look at: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html

**TASK 5.1(10 Points):** Using all the data compiled from before find a person that matches all the features from the profile

- put the name of the culprit in a variable called **"culprit"**

In [24]:
# Write your code here
culprit_df = pd.merge(profiles_df, show_df, on='ID', how='inner')

culprit_df[
    culprit_df['Eye_Color'].isin(potential_eye_colors) &
    culprit_df['Skin_Color'].isin(potential_skin_colors) &
    culprit_df['Hair_Color'].isin(potential_hair_colors) &
    culprit_df['Age'].isin(range(smallest_age, largest_age+1)) &
    culprit_df['Height'].isin(range(smallest_height, largest_height+1))]

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height,Age,Ticket_Number,Ticket_Color
15,P029,Gary Phillips,2004-05-12,fourth floor,green,orange,violet,160,21,63045332,green
59,P234,Miguel Day,2003-02-05,second floor,green,orange,orange,154,22,65162765,yellow
90,P025,Arthur Gutierrez,1999-05-27,NaN,blue,red,green,153,26,31002643,yellow
146,P202,Ishan Kar,1990-07-12,second floor,orange,green,blue,170,35,36984005,red

In [20]:
culprit_df[culprit_df.duplicated(subset=['ID'], keep=False)]

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height,Age,Ticket_Number,Ticket_Color
1,P158,Karen Roberts,1981-05-11,NaN,red,yellow,blue,172,44,67113019,yellow
3,P136,Jodi Mccarty,1987-07-22,NaN,orange,orange,red,198,38,3439786,blue
4,P160,Joshua Diaz,1959-04-09,second floor,yellow,green,red,161,66,47060216,green
6,P136,Jodi Mccarty,1987-07-22,NaN,orange,orange,red,198,38,3439786,blue
24,P166,Adrian Black,1976-01-13,fourth floor,red,violet,yellow,176,49,66168819,red
28,P145,Robert Lee,1999-11-07,second floor,orange,indigo,violet,173,25,39491651,yellow
34,P132,Amanda Morales,1971-07-22,NaN,violet,blue,green,192,54,50269975,red
35,P293,Mrs. Barbara Harris,1988-01-05,fourth floor,indigo,blue,orange,197,37,66188567,green
36,P158,Karen Roberts,1981-05-11,NaN,red,yellow,blue,172,44,67113019,yellow
41,P139,Michael Archer,1997-07-13,second floor,orange,yellow,red,189,28,63745130,yellow
42,P156,Alexandria Stephens,1981-03-25,third floor,yellow,yellow,orange,152,44,27344711,yellow
44,P143,Tyler Thomas,1996-07-16,NaN,yellow,indigo,violet,150,29,59598056,green
45,P162,Rhonda Baxter,1975-03-22,lobby,orange,yellow,yellow,194,50,61489246,blue
47,P300,Michael Mendez,1964-11-10,NaN,violet,yellow,blue,192,60,56763889,blue
53,P137,David Collins,1988-09-08,third floor,red,blue,yellow,198,37,65873942,red
54,P166,Adrian Black,1976-01-13,fourth floor,red,violet,yellow,176,49,66168819,red
55,P167,Denise Rodriguez,2005-11-26,NaN,yellow,yellow,yellow,196,19,1823016,blue
57,P167,Denise Rodriguez,2005-11-26,NaN,yellow,yellow,yellow,196,19,1823016,blue
64,P138,Andrew Sharp,1965-07-18,fourth floor,green,orange,green,172,60,43995703,blue
67,P297,Michelle Weber,1993-05-03,NaN,yellow,red,orange,190,32,55710602,green
71,P152,Cassandra Dunn,1992-07-08,third floor,yellow,yellow,indigo,151,33,64066630,blue
73,P133,Patrick Farrell,2001-12-10,second floor,orange,indigo,green,163,23,1659823,red
74,P137,David Collins,1988-09-08,third floor,red,blue,yellow,198,37,65873942,red
81,P165,Nicholas Cooper,1985-05-20,fourth floor,yellow,yellow,indigo,199,40,63669444,blue
84,P135,Aaron Weber,1960-08-21,second floor,orange,yellow,yellow,151,65,54314497,green
85,P131,Rebecca Davis,1970-04-30,NaN,green,violet,yellow,157,55,61367768,red
87,P300,Michael Mendez,1964-11-10,NaN,violet,yellow,blue,192,60,56763889,blue
89,P142,Andrew Walker,1981-11-07,lobby,indigo,green,indigo,193,43,2238676,red
92,P159,Danny Pearson,1995-12-06,fourth floor,red,red,blue,187,29,54158103,green
94,P293,Mrs. Barbara Harris,1988-01-05,fourth floor,indigo,blue,orange,197,37,66188567,green
97,P133,Patrick Farrell,2001-12-10,second floor,orange,indigo,green,163,23,1659823,red
98,P135,Aaron Weber,1960-08-21,second floor,orange,yellow,yellow,151,65,54314497,green
103,P132,Amanda Morales,1971-07-22,NaN,violet,blue,green,192,54,50269975,red
107,P139,Michael Archer,1997-07-13,second floor,orange,yellow,red,189,28,63745130,yellow
112,P297,Michelle Weber,1993-05-03,NaN,yellow,red,orange,190,32,55710602,green
117,P159,Danny Pearson,1995-12-06,fourth floor,red,red,blue,187,29,54158103,green
122,P294,Bradley Jimenez,1974-02-11,second floor,red,red,red,196,51,36224262,green
123,P294,Bradley Jimenez,1974-02-11,second floor,red,red,red,196,51,36224262,green
124,P162,Rhonda Baxter,1975-03-22,lobby,orange,yellow,yellow,194,50,61489246,blue
127,P143,Tyler Thomas,1996-07-16,NaN,yellow,indigo,violet,150,29,59598056,green
128,P298,Marie Flynn,1998-02-20,third floor,green,orange,green,194,27,37592884,green
130,P156,Alexandria Stephens,1981-03-25,third floor,yellow,yellow,orange,152,44,27344711,yellow
134,P298,Marie Flynn,1998-02-20,third floor,green,orange,green,194,27,37592884,green
137,P145,Robert Lee,1999-11-07,second floor,orange,indigo,violet,173,25,39491651,yellow
143,P131,Rebecca Davis,1970-04-30,NaN,green,violet,yellow,157,55,61367768,red
148,P142,Andrew Walker,1981-11-07,lobby,indigo,green,indigo,193,43,2238676,red
154,P152,Cassandra Dunn,1992-07-08,third floor,yellow,yellow,indigo,151,33,64066630,blue
167,P165,Nicholas Cooper,1985-05-20,fourth floor,yellow,yellow,indigo,199,40,63669444,blue
171,P160,Joshua Diaz,1959-04-09,second floor,yellow,green,red,161,66,47060216,green
173,P138,Andrew Sharp,1965-07-18,fourth floor,green,orange,green,172,60,43995703,blue

**TASK 5.2 (2 Points):** Check if your culprit is correct!

interrogate your culprit to see if you got the correct person

In [21]:
# Write your code here

In [22]:
# REMOVE LATER

with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(important_witnesses['Statement'][important_witnesses['Statement'].str.contains('years old', case=False)])

10    I saw someone that looks to be 30 years old ac...
15    I saw someone that looks to be 23 years old ac...
16    I saw someone that looks to be 21 years old ac...
17    I saw someone that looks to be 22 years old ac...
23    I saw someone that looks to be 22 years old ac...
29    I saw someone that looks to be 21 years old ac...
36    I saw someone that looks to be 24 years old ac...
43    I saw someone that looks to be 23 years old ac...
44    I saw someone that looks to be 22 years old ac...
45    I saw someone that looks to be 35 years old ac...
58    I saw someone that looks to be 21 years old ac...
Name: Statement, dtype: object